import localFont from "next/font/local";
import "./globals.css";
import Footer from "@/components/Shared/Footer";

import AuthProvider from "@/services/AuthProvider";
import Navbar from "@/components/Navbar/Navbar";




const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        <AuthProvider>
          {/* navbar */}
          <Navbar></Navbar>
          <section className="container mx-auto">
            {children}
          </section>

          {/* footer */}
          <Footer></Footer>
        </AuthProvider>

      </body>
    </html>
  );
}
